export const IS_FETCHING_PLAYER = 'IS_FETCHING_PLAYER';
export const DID_FETCH_PLAYER = 'DID_FETCH_PLAYER';

export const DID_CONNECT_SOCKET = 'DID_CONNECT_SOCKET';
export const DID_JOIN_CHANNEL = 'DID_JOIN_CHANNEL';
export const DID_FAIL_CHANNEL = 'DID_FAIL_CHANNEL';
