export const WILL_FETCH_PLAYER = 'WILL_FETCH_PLAYER';
export const DID_FETCH_PLAYER = 'DID_FETCH_PLAYER';

export const DID_CONNECT_SOCKET = 'DID_CONNECT_SOCKET';
export const DID_JOIN_CHANNEL = 'DID_JOIN_CHANNEL';
export const DID_FAIL_CHANNEL = 'DID_FAIL_CHANNEL';

export const WILL_CREATE_GAME = 'WILL_CREATE_GAME';
export const DID_CREATE_GAME = 'DID_CREATE_GAME';

export const WILL_FALL_CHECKER = 'WILL_FALL_CHECKER';
export const DID_LAND_CHECKER = 'DID_LAND_CHECKER';
export const DID_UPDATE_CHECKER = 'DID_UPDATE_CHECKER';

export const DID_TAKE_TURN = 'DID_TAKE_TURN';
export const DID_SWITCH_TURN = 'DID_SWITCH_TURN';

export const WILL_JOIN_GAME = 'WILL_JOIN_GAME';
export const DID_JOIN_GAME = 'DID_JOIN_GAME';

export const WILL_UPDATE_GAME = 'WILL_UPDATE_GAME';
export const DID_UPDATE_GAME = 'DID_UPDATE_GAME';
export const DID_WIN_GAME = 'DID_WIN_GAME';

export const WILL_RESET_BOARD = 'WILL_RESET_BOARD';
export const WILL_UPDATE_BOARD = 'WILL_UPDATE_BOARD';
export const DID_UPDATE_BOARD = 'DID_UPDATE_BOARD';
export const DID_WIN_BOARD = 'DID_WIN_BOARD';

export const WILL_PLAY_ONLINE = 'WILL_PLAY_ONLINE';
export const WILL_PLAY_OFFLINE = 'WILL_PLAY_OFFLINE';

export const DID_JOIN_LOBBY = 'DID_JOIN_LOBBY';

export const ENQUEUE_WIN = 'ENQUEUE_WIN';
